= Contacts API

=== Create
Example how to create a new contact that will be stored in your Ez Texting contact list
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var contact = new Contact
    {
        FirstName = "Piglet",
        LastName = "Notail",
        PhoneNumber = "2123456785",
        Email = "piglet@small-animals-alliance.org",
        Note = "It is hard to be brave, when you are only a Very Small Animal.",
        Groups = new List<string>() {"Friends", "Neighbors"}
    };
    Contact stored = client.ContactsApi.Create(contact);
    Console.WriteLine(stored);

=== Update
Example how to update a contact stored in your Ez Texting contact list
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var contact = new Contact
    {
        Id = "4f0b5720734fada368000000",
        PhoneNumber = "2123450000",
    };
    Contact updated = client.ContactsApi.Update(contact);
    Console.WriteLine(updated);

=== Get one contact
Get a single contact stored in your Ez Texting contact list.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    Contact contact = client.ContactsApi.Get("4f0b5720734fada368000000");
    Console.WriteLine(contact);

=== Get multiple contacts
Get a list of contacts stored in your Ez Texting contact list.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var request = new GetContactsRequest
    {
        // search contacts by first name / last name / phone number
        Query = QueryProperty.FirstName,
        // source of contacts, available values: 'Unknown', 'Manually Added', 'Upload', 'Web Widget', 'API', 'Keyword'
        Source = SourceType.Manual,
        OptOut = true,
        // name of the group the contacts belong to
        Group = "My Friends",
        // property to sort by. Available values: PhoneNumber, FirstName, LastName, CreatedAt
        SortBy = SortProperty.CreatedAt,
        // sorting asc, desc
        SortType = SortType.Desc,
        // number of results to retrieve. By default, 10 most recently added contacts are retrieved.
        ItemsPerPage = 10,
        // page of results to retrieve
        Page = 7
    };
    IList<Contact> contacts = client.ContactsApi.Get(request);
    Console.WriteLine("multiple contacts: " + contacts);

=== Delete
Delete a contact stored in your Ez Texting contact list
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    client.ContactsApi.Delete("4f0b5720734fada368000000");