= Inbox API

=== Get a message
Get a single incoming text messages in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    InboxMessage message = client.InboxApi.GetMessage(15168146L);
    Console.WriteLine("inbox message: " + message);

=== Get multiple messages
Get some incoming text messages in your Ez Texting Inbox depending on search criteria
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var request = new GetMessagesRequest
    {
        // messages with "car service" text
        Search = "car service",
        // get messages from particular folder
        FolderId = 20,
        Type = MessageType.Sms,
        // sorting order asc/desc
        SortType = SortType.Desc,
        // property to sort by. Available values: ReceivedOn, PhoneNumber, Message
        SortBy = SortProperty.ReceivedOn,
        // number of results to retrieve. By default, 10 most recent incoming messages are retrieved.
        ItemsPerPage = 10,
        // page of results to retrieve. 1st page is returned by default
        Page = 1
    };
    IList<InboxMessage> messages = client.InboxApi.GetMessages(request);
    Console.WriteLine("inbox messages: " + messages);

=== Move message to a folder
Moves an incoming text message in your Ez Texting Inbox to a specified folder. You may include multiple
 Message IDs to move multiple messages to same folder.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    client.InboxApi.MoveMessage(123, 456);
    // or move several messages
    client.InboxApi.MoveMessages(new List<long> { 123, 124, 125, 126 }, 456);

=== Delete a message
Delete an incoming text message in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    client.InboxApi.DeleteMessage(354421);

=== Create a folder
Create a folder in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    Folder created = client.InboxApi.CreateFolder("Work messages");
    Console.WriteLine("Created folder: " + created);

=== Update a folder
Update the name of a folder in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var folder = new Folder
    {
        Id = 3434,
        Name = "New name"
    };
    client.InboxApi.UpdateFolder(folder);

=== Get a folder
Get a single folder in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var folder = client.InboxApi.GetFolder(343434);
    Console.WriteLine(folder);

=== Get all folders
Get all folders in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    IList<Folder> folders = client.InboxApi.GetFolders();
    Console.WriteLine("Get all folders: " + folders);

=== Delete a folder
Delete a folder in your Ez Texting Inbox
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    client.InboxApi.DeleteFolder(354421);