= Media Library API

=== Create
Create a new media file that will be stored in your Ez Texting media library
[source,csharp]
    EzTextingClient client = new EzTextingClient("api_login", "api_password");
    MediaFile media = client.MediaLibraryApi.Create("http://your-storage.com/media.mp3");
    Console.WriteLine(media);

=== Get one media file
Get a single file stored in your Ez Texting media library.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    MediaFile mediaFile = client.MediaLibraryApi.Get(343434);
    Console.WriteLine(mediaFile);

=== Get multiple files
Get a list of media files stored in your Ez Texting media library.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var request = new GetRequest
    {
        // sort asc/desc
        SortType = SortType.Desc,
        // number of results to retrieve. By default, first 10 groups sorted in alphabetical order are retrieved.
        ItemsPerPage = 10,
        // page of results to retrieve
        Page = 7
    };
    IList<MediaFile> files = client.MediaLibraryApi.Get(request);
    Console.WriteLine("multiple files: " + files);

=== Delete
Delete file in your Ez Texting media library
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    client.MediaLibraryApi.Delete(354421);