= Messaging API

=== Sending SMS/MMS messages
Send SMS/MMS messages via the short code 313131 (393939 In Canada) to a single phone number or an array of phone numbers.
Example how to send SMS message:
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var sms = new SmsMessage
    {
        Subject = "test subject",
        Message = "this is sms message",
        PhoneNumbers = new List<string> {"1234567890", "2345678900", "3456789000"},
        Groups = new List<string> {"group1", "group2", "group3"},
        StampToSend = DateTime.Now
    };
    SmsMessage response = client.MessagingApi.Send(msg);
    Console.WriteLine("send sms message response: " + response);

or MMS message:
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var mms = new MmsMessage
    {
        // media file ID in your account's media library
        FileId = 123,
        Subject = "Subject",
        Message = "text message"
        // set StampToSend if we want to schedule this message
        StampToSend = DateTime.Now
    };
    MmsMessage response = client.MessagingApi.Send(msg);
    Console.WriteLine("send mms message response: " + response);

=== Sending voice broadcast messages
Send voice broadcast messages to an array of phone numbers or a Group in your Ez Texting account. You can use
 a file stored in your Ez Texting account as the source, or include the URL of a compatible file in the request.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    var message = new VoiceMessage
    {
        // outbound phone number
        CallerPhoneNumber = "1234567890",
        Name = "test broadcast",
        // or add file from media library
        // VoiceFile = "greeting_sound",
        VoiceSource = "http://yoursite.com/voice.mp3",
        PhoneNumbers = new List<string> {"1234567890", "2345678900", "3456789000"},
        Groups = new List<string> {"group1", "group2", "group3"},
        // send immediately
        StampToSend = DateTime.Now
    };
    VoiceMessage response = client.MessagingApi.Send(msg);
    Console.WriteLine("voice message response: " + response);

=== Delivery reports
Get a report for specific delivery status of a message you have sent.
[source,csharp]
    EzTextingClient client = new EzTextingClient("login", "password");
    DeliveryReport report = client.MessagingApi.GetReport(56491730);
    Console.WriteLine("Delivery Report: " + report);

=== Detailed delivery reports
Get a report for specific delivery status of a message you have sent and the phone numbers for that delivery type.
[source,csharp]
    EzTextingClient client = new EzTextingClient("api_login", "api_password");
    IList<long> report = client.MessagingApi.GetDetailedReport(56491730, DeliveryStatus.Bounced);
    Console.WriteLine("Detailed Delivery Reports: " + report);